# -*- coding: utf-8 -*-
"""threads.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aaHhlwoPZ2sd0wfZYcXCJCfIEHvb8YVN
"""

from time import sleep

print("Olá bootcampers")
for i in range(10):
  print(i)
  sleep(.5)

print("IGTI")

from threading import Thread

class IGThread(Thread):
  def __init__(self, texto, tempo):
    self.texto = texto
    self.tempo = tempo

    super().__init__()

  def run(self):
    sleep(self.tempo)
    print(self.texto)

t1 = IGThread('IGTI Thread 1', 5)
t1.start()


t2 = IGThread('IGTI Thread 2', 8)
t2.start()

t3 = IGThread('IGTI Thread 3', 17)
t3.start()

t4 = IGThread('IGTI Thread 4', 2)
t4.start()

for i in range(20):
  print(i)
  sleep(1)